---
title: "Short Projects Dates"
---

Short programming projects are due on the same day as programming problems. While the instructions for programming problems are on the website, instructions for short projects will be available only during our weekly 50-minute in-person lab sessions. 

The 2 lowest grade for short programming projects will be dropped at the end of the semester. There will be one lab session for you to work on a maximum of one short programming project submission you have missed.

To schedule your lab session go to [the weekly lab session spreadsheet](https://docs.google.com/spreadsheets/d/18gA1RiiaNIVF97qJo9bwnF25gwK3Jd60QQPN37plN6o/edit?usp=sharing).

# Lab Schedule

This is for information only. 

* [Lab 01](lab01.html): Jan 04 to Jan 28 
* [Lab 02](lab02.html): Jan 29 to Feb 04 
* [Lab 03](lab03.html): Feb 05 to Feb 11 
* [Lab 04](lab04.html): Feb 12 to Feb 18
* [Lab 05](lab05.html): Feb 19 to Feb 27 
* [Lab 06](lab06.html): Feb 28 to Mar 04 
* [Lab 07](lab07.html): Mar 05 to Mar 18 
* CATCH UP WEEK: Mar 19 to Mar 25
* [Lab 08](lab08.html): Mar 26 to Apr 01 
* [Lab 09](lab09.html): Apr 02 to Apr 08
* [Lab 10](lab10.html): Apr 09 to Apr 15
* [Lab 11](lab11.html): Apr 16 to Apr 22
* [Lab 12](lab12.html): Apr 23 to May 01