---
title: "Program Decomposition (slides)"
format: revealjs
slide-number: true
---

# CSC 110 Program Decomposition

## Quick Review

-   round(number_to_round, ndigits). ndigits if omitted or set to None, defaults to 0 (rounds to the nearest integer)

-   integer versus float (why bother with integers?)

## The Purpose of Autograding

-   Autograders are for giving class staff the resources to grade a lot of code (and thereby giving students the chance to practice coding often)

-   Autograders are not for replacing the process of comparing your code's output with the given expected output, and identifying errors yourself before submitting

-   You should be ~90% sure that your code works correctly *before* submitting it to Gradescope

## Program decomposition

-   Program decomposition refers to the process of breaking down a complex program into smaller, more manageable, and understandable parts or components.

-   It avoids unnecessary common code and improves the structural quality of code.


## Class activity one

Read the code, discuss with your table and write an answer on your white board: what problem does this code solve?

```{python}
#| echo: true
#| eval: false
cube_len = int(input("Cube length? "))
box_w = int(input("Box width? "))
box_h = int(input("Box height? "))
box_l = int(input("Box length? "))
fit_w = box_w // cube_len
fit_h = box_h // cube_len
fit_l = box_l // cube_len
print(str(fit_w) + " Rubik's cubes will fit width-wise.")
print(str(fit_h) + " Rubik's cubes will fit height-wise.")
print(str(fit_l) + " Rubik's cubes will fit length-wise.")
res = fit_w * fit_h * fit_l
print(str(res)+" Rubik's cubes will fit in that container.")
```

## How to decompose this program?

-   This program is confusing to read! And it has a *lot* of repeated code. Can we separate out some of the code into functions, and then call the functions?
-   Before we do that, we need to identify what can grouped together, and what can't. Which lines fall into the former category, and which lines fall into the latter? Discuss, and write your answers on your white boards.

## Line Grouping: Activity two

-   Which lines are similar? Which lines are unique?

```{python}
#| echo: true
#| eval: false
cube_len = int(input("Cube length? "))
box_w = int(input("Box width? "))
box_h = int(input("Box height? "))
box_l = int(input("Box length? "))
fit_w = box_w // cube_len
fit_h = box_h // cube_len
fit_l = box_l // cube_len
print(str(fit_w) + " Rubik's cubes will fit width-wise.")
print(str(fit_h) + " Rubik's cubes will fit height-wise.")
print(str(fit_l) + " Rubik's cubes will fit length-wise.")
res = fit_w * fit_h * fit_l
print(str(res)+" Rubik's cubes will fit in that container.")
```


## Activity two -- answers

Read the code and write the questions:

-   which lines of code are similar? 

    -   line 2-4, line 5-7, line 8-10

-   which lines of code are unique? 

    -   line 1, line 11-12

## Activity two -- continued

Which lines can be grouped together into a function?

- line 1, 5, 8:

```{python}
#| echo: true
#| eval: false
box_w = int(input("Box width? ")) 

fit_w = box_w // cube_len

print(str(fit_w) + " Rubik's cubes will fit width-wise.")
```

What are the parameters of this function? In other words, what information must be known beforehand?

## Activity two -- answers continued

Given the length of a cube and the name of a box side:

-   It prompts you to the enter the length of the side

-   It calculates the number of cube that can fit in the side

-   It prints the message and return the number.


## Write a function

Write function `get_fit` that takes the length of a `cube` (integer) and the name of a `side` (string)

-   It prompts you to the enter the length of the `side`

-   It calculates the number of `cube` that can fit in the `side`

-   It print the message and return the number.

```{python}
#| echo: true
#| eval: false
def main():
    cube_len = int(input("Cube length? "))
    fit_w = get_fit(cube_len, 'width')
    fit_h = get_fit(cube_len, 'height')
    fit_l = get_fit(cube_len, 'length')
    result = fit_w * fit_h * fit_l
    print(str(result) + " Rubik's cubes will fit in that container.")
```

## Write a function -- answer

```{python}
#| echo: true
#| eval: false
def get_fit(cube, side):
    large = int(input("Box {}? ".format(side)))
    fit = large // cube
    print("{} Rubik's cubes will fit {}-wise.".format(fit, side))
    return fit

def main():
    cube_len = int(input("Cube length? "))
    fit_w = get_fit(cube_len, 'width')
    fit_h = get_fit(cube_len, 'height')
    fit_l = get_fit(cube_len, 'length')
    result = fit_w * fit_h * fit_l
    print(str(result) + " Rubik's cubes will fit in that container.")

main()
```

